//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditStatistics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://milkyway.cs.rpi.edu/milkyway/results.php?hostid=959559&offset=0&show_name" +
            "s=0&state=4&appid=")]
        public string InitialUrl {
            get {
                return ((string)(this["InitialUrl"]));
            }
            set {
                this["InitialUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] HostList {
            get {
                return ((string[])(this["HostList"]));
            }
            set {
                this["HostList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskForStudy {
            get {
                return ((bool)(this["AskForStudy"]));
            }
            set {
                this["AskForStudy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskForBoinctasks {
            get {
                return ((bool)(this["AskForBoinctasks"]));
            }
            set {
                this["AskForBoinctasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] AppList {
            get {
                return ((string[])(this["AppList"]));
            }
            set {
                this["AppList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] RemoteHosts {
            get {
                return ((string[])(this["RemoteHosts"]));
            }
            set {
                this["RemoteHosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimeoutProj {
            get {
                return ((int)(this["TimeoutProj"]));
            }
            set {
                this["TimeoutProj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TimeoutPC {
            get {
                return ((int)(this["TimeoutPC"]));
            }
            set {
                this["TimeoutPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] MasterUrls {
            get {
                return ((string[])(this["MasterUrls"]));
            }
            set {
                this["MasterUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] BGshortnames {
            get {
                return ((string[])(this["BGshortnames"]));
            }
            set {
                this["BGshortnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] BGstudies {
            get {
                return ((string[])(this["BGstudies"]));
            }
            set {
                this["BGstudies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] BGurls {
            get {
                return ((string[])(this["BGurls"]));
            }
            set {
                this["BGurls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PC_CPU_GPU {
            get {
                return ((string)(this["PC_CPU_GPU"]));
            }
            set {
                this["PC_CPU_GPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] AllHostList {
            get {
                return ((string[])(this["AllHostList"]));
            }
            set {
                this["AllHostList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] SprintPstart {
            get {
                return ((string[])(this["SprintPstart"]));
            }
            set {
                this["SprintPstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] SprintPend {
            get {
                return ((string[])(this["SprintPend"]));
            }
            set {
                this["SprintPend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SprintGrelease {
            get {
                return ((string)(this["SprintGrelease"]));
            }
            set {
                this["SprintGrelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SprintGend {
            get {
                return ((string)(this["SprintGend"]));
            }
            set {
                this["SprintGend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] SprintPduration {
            get {
                return ((string[])(this["SprintPduration"]));
            }
            set {
                this["SprintPduration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] AlreadyBunkered {
            get {
                return ((string[])(this["AlreadyBunkered"]));
            }
            set {
                this["AlreadyBunkered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalHostName {
            get {
                return ((string)(this["LocalHostName"]));
            }
            set {
                this["LocalHostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int nMasterUrls {
            get {
                return ((int)(this["nMasterUrls"]));
            }
            set {
                this["nMasterUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] RC_systems {
            get {
                return ((string[])(this["RC_systems"]));
            }
            set {
                this["RC_systems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] RC_usernames {
            get {
                return ((string[])(this["RC_usernames"]));
            }
            set {
                this["RC_usernames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string[] RC_passwords {
            get {
                return ((string[])(this["RC_passwords"]));
            }
            set {
                this["RC_passwords"] = value;
            }
        }
    }
}
